# Generated by Django 5.1.1 on 2026-02-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0002_chessplayer_gamelobby_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamelobby",
            name="game_type",
            field=models.CharField(
                choices=[("chess", "Chess")],
                default="chess",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="gamelobby",
            name="lobby_size",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="gamelobby",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_lobbies",
                to="auth_system.chessplayer",
            ),
        ),
    ]
