# Generated by Django 5.1.1 on 2026-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_gamelobby_game_type_gamelobby_stake_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessplayer',
            name='chess_cookie_header',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chessplayer',
            name='chess_csrf_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chessplayer',
            name='chess_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='chess_challenge_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='chess_game_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='chess_game_legacy_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='chess_state',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
